### General
exp_name: test 
seed: 7
torch_anomaly_detection: True

### Task choice
opfdata: False
powergraph: False
solarcube: False
buildingelectricity: False
windfarm: True

### Subtask choice
opfdata_subtask: 'train_small_test_medium'
powergraph_subtask: 'demand_not_served_regression'
solarcube_subtask: 'odd_time_area'
buildingelectricity_subtask: 'odd_time_buildings92'
windfarm_subtask: 'odd_time_predict48h'

### Data
data_frac: 0.01
train_frac: 1

### Canonical data representation
std_vect_dim: 512

### MultiSenseNet
n_heads: 16
n_layers: 12
dim_feedforward: 4096
dropout: 0.1
max_seq_len: 4096
layer_norm_eps: 1.e-5
activation: gelu

### Training loop
dtype: float64 # choose float64 or float32
device_gpu: True
batch: 2
epochs: 10
