### General
seed: None
torch_anomaly_detection: True

### Canonical data representation
std_vect_dim: 1024

### Transformer backbone architecture
n_heads: 16
n_layers: 12
dim_feedforward: 4096
dropout: 0.1
max_seq_len: 4096
layer_norm_eps: 1.e-5

### Training Loop
dtype: float64
device_gpu: True
batch: 2


